# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='namn'),
            preserve_default=False,
        ),
    ]
