# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
